# Generated by Django 4.0.2 on 2022-05-07 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='prod_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='prod_regNo',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
