# Generated by Django 3.2.6 on 2022-05-08 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0004_coupon_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
