# Generated by Django 3.2.6 on 2022-05-22 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0006_wishlist_wishlistitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='ref_code',
        ),
    ]
