# Generated by Django 4.0.2 on 2022-04-24 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cl_regNo', models.TextField(unique=True)),
                ('cl_name', models.TextField(unique=True)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=50)),
                ('field_name', models.EmailField(max_length=254)),
            ],
        ),
    ]
