# Generated by Django 3.2.6 on 2022-05-22 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('User', 'User'), ('Vender', 'Vender')], default='User', max_length=50),
        ),
    ]
